from __future__ import annotations

from pathlib import Path
from typing import Any, Callable, Dict, Optional, Protocol

from app.application.models import (
    MediaRecord,
    ScanProgress,
    ScanResult,
    ScannedFile,
    TagMiningProgress,
)


ProgressCallback = Callable[[ScanProgress], None]
TagMiningProgressCallback = Callable[[TagMiningProgress], None]


class EmbeddingModelPort(Protocol):
    def name(self) -> str: ...

    def is_available(self) -> bool: ...

    def unavailable_reason(self) -> str: ...

    def embed(self, texts: list[str]) -> list[list[float]]: ...


class RerankerModelPort(Protocol):
    def name(self) -> str: ...

    def is_available(self) -> bool: ...

    def unavailable_reason(self) -> str: ...

    def rerank(self, query: str, candidates: list[str]) -> list[float]: ...


class TagGeneratorPort(Protocol):
    def name(self) -> str: ...

    def is_available(self) -> bool: ...

    def unavailable_reason(self) -> str: ...

    def generate_tags(self, title: str, max_tags: int = 8) -> list[str]: ...


class TokenizerPort(Protocol):
    def name(self) -> str: ...

    def is_available(self) -> bool: ...

    def unavailable_reason(self) -> str: ...

    def tokenize(self, text: str) -> list[str]: ...


class LibraryRepositoryPort(Protocol):
    def open(self, root: Path) -> None: ...

    def close(self) -> None: ...

    def root_path(self) -> Optional[Path]: ...

    def raw_data(self) -> Dict[str, Any]: ...

    def videos(self) -> Dict[str, Dict[str, Any]]: ...

    def save(self) -> None: ...

    def apply_scan(self, scanned_files: list[ScannedFile]) -> ScanResult: ...

    def apply_media_records(self, media_records: list[MediaRecord]) -> None: ...

    def apply_ai_title_tags(
        self,
        tags_by_video_id: Dict[str, list[str]],
        target_video_ids: Optional[list[str]] = None,
    ) -> int: ...

    def clear_ai_title_tags(self) -> int: ...

    def mark_title_tag_mined(self, video_ids: list[str], mined_epoch: int) -> None: ...

    def upsert_tag_candidates(self, hits_by_tag: Dict[str, list[str]]) -> int: ...

    def list_tag_candidates(self, statuses: Optional[list[str]] = None) -> list[Dict[str, Any]]: ...

    def list_pending_tag_candidates(self) -> list[Dict[str, Any]]: ...

    def list_tag_blacklist(self) -> list[Dict[str, Any]]: ...

    def list_blacklist_terms(self) -> list[str]: ...

    def approve_tag_candidates(self, candidate_ids: list[int]) -> Dict[str, int]: ...

    def approve_tag_candidates_with_mapping(
        self,
        candidate_ids: list[int],
        target_tag_id: int,
    ) -> Dict[str, int]: ...

    def blacklist_tag_candidates(self, candidate_ids: list[int]) -> Dict[str, int]: ...

    def clear_pending_tag_candidates(self) -> int: ...

    def reject_tag_candidates(self, candidate_ids: list[int]) -> int: ...

    def requeue_tag_candidates(self, candidate_ids: list[int]) -> int: ...

    def list_tags(self) -> list[Dict[str, Any]]: ...

    def list_concept_mappings(self) -> list[Dict[str, Any]]: ...

    def list_tag_alias_memory(self) -> list[Dict[str, Any]]: ...

    def upsert_tag_alias_memory(
        self,
        alias_to_tag_id: Dict[str, int],
        source: str = "manual",
        status: str = "verified",
    ) -> int: ...

    def upsert_tag_alias_suggestions(
        self, suggestions: list[Dict[str, Any]]
    ) -> int: ...

    def list_pending_tag_alias_suggestions(self) -> list[Dict[str, Any]]: ...

    def approve_tag_alias_suggestions(self, suggestion_ids: list[int]) -> Dict[str, int]: ...

    def reject_tag_alias_suggestions(self, suggestion_ids: list[int]) -> int: ...

    def upsert_tags(self, names: list[str]) -> int: ...

    def delete_tags_by_ids(self, tag_ids: list[int]) -> int: ...

    def add_manual_tag_to_video(self, video_id: str, tag_name: str) -> bool: ...

    def remove_tag_from_video(self, video_id: str, tag_name: str) -> int: ...


class ScannerPort(Protocol):
    def scan(
        self, root: Path, progress: Optional[ProgressCallback] = None
    ) -> list[ScannedFile]: ...


class MediaIndexerPort(Protocol):
    def index(
        self,
        root: Path,
        scanned_files: list[ScannedFile],
        progress: Optional[ProgressCallback] = None,
    ) -> list[MediaRecord]: ...


class FileOpenerPort(Protocol):
    def open_file(self, path: Path) -> None: ...


class ScanLoggerPort(Protocol):
    def set_library_root(self, root: Path) -> None: ...

    def begin_scan(self, total_files: int) -> None: ...

    def log_file_discovered(self, scanned_file: ScannedFile) -> None: ...

    def log_media_record(self, record: MediaRecord) -> None: ...

    def end_scan(self, result: ScanResult, elapsed_ms: int) -> None: ...

    def log_error(self, stage: str, message: str, rel_path: str = "") -> None: ...

    def list_logs(self, limit: int = 30) -> list[Path]: ...

    def latest_log_path(self) -> Optional[Path]: ...

    def read_log(self, log_path: Path) -> list[Dict[str, Any]]: ...


class TagMiningLoggerPort(Protocol):
    def set_library_root(self, root: Path) -> None: ...

    def begin_run(self, total_videos: int, config: Dict[str, Any]) -> None: ...

    def log_event(self, event: str, payload: Dict[str, Any]) -> None: ...

    def log_video_processed(
        self, video_id: str, rel_path: str, terms: list[str], selected_terms: list[str]
    ) -> None: ...

    def log_summary(self, summary: Dict[str, Any]) -> None: ...

    def log_error(self, stage: str, message: str, rel_path: str = "") -> None: ...

    def list_logs(self, limit: int = 30) -> list[Path]: ...

    def latest_log_path(self) -> Optional[Path]: ...

    def read_log(self, log_path: Path) -> list[Dict[str, Any]]: ...


class AppRuntimeLoggerPort(Protocol):
    def set_library_root(self, root: Path) -> None: ...

    def log_event(
        self,
        event: str,
        *,
        level: str = "info",
        module: str = "",
        action: str = "",
        message: str = "",
        payload: Optional[Dict[str, Any]] = None,
        request_id: str = "",
    ) -> None: ...

    def list_logs(self, limit: int = 30) -> list[Path]: ...

    def latest_log_path(self) -> Optional[Path]: ...

    def read_log(self, log_path: Path) -> list[Dict[str, Any]]: ...
